name = "BranchAndPrune"
uuid = "d3bc4f2e-91e6-11e9-365e-cd067da536ce"
authors = ["Benoît Richard <kolaru@hotmail.com>"]
version = "0.2.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"

[compat]
julia = "1.6"
AbstractTrees = "0.4"
